package hibernate.Proyecto_dgc;
// Generated 23 ene 2025, 10:53:15 by Hibernate Tools 6.3.2.Final

import java.sql.Date;

/**
 * Notificaciones generated by hbm2java
 */
public class Notificaciones implements java.io.Serializable {

	private Integer idNotificacion;
	private Usuario usuario;
	private Date fecha;
	private String contenido;

	public Notificaciones() {
	}

	public Notificaciones(Usuario usuario, Date fecha, String contenido) {
		this.usuario = usuario;
		this.fecha = fecha;
		this.contenido = contenido;
	}

	public Integer getIdNotificacion() {
		return this.idNotificacion;
	}

	public void setIdNotificacion(Integer idNotificacion) {
		this.idNotificacion = idNotificacion;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(java.util.Date fecha) {
	    this.fecha = (Date) fecha;
	}


	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

}
