/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import DTO.CochesDTO;
import javax.swing.JOptionPane;
import servicio.CochesServicio;

/**
 *
 * @author Laura
 */
public class Crear extends javax.swing.JFrame {

    private CochesServicio cochesServicio;

    /**
     * Creates new form Crear
     */
    public Crear(CochesServicio cochesServicio) {
        if (cochesServicio == null) {
            throw new IllegalArgumentException("CochesServicio no puede ser null");
        }
        this.cochesServicio = cochesServicio;

        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Para cerrar solo esta ventana
        setLocationRelativeTo(null);

        cargarMarcas();
        cargarModelosPorMarca();

        // Colores y configuraciones de tamaño fijo
        configurarEncabezadoTabla();
        setResizable(false); // Evitar que la ventana se pueda redimensionar
    }


    private void cargarMarcas() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Seleccione una marca");
        for (String marca : cochesServicio.obtenerMarcas()) {
            jComboBox1.addItem(marca);
        }
        jComboBox1.addActionListener(e -> cargarModelosPorMarca());
    }

    private void cargarModelosPorMarca() {
        String marcaSeleccionada = (String) jComboBox1.getSelectedItem();
        if (marcaSeleccionada != null && !marcaSeleccionada.equals("Seleccione una marca")) {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Seleccione un modelo");
            for (String modelo : cochesServicio.obtenerModelosPorMarca(marcaSeleccionada)) {
                jComboBox2.addItem(modelo);
            }
        } else {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Seleccione un modelo");
        }
    }

    private void agregarVehiculo() {
    String matricula = jTextField1.getText().trim();
    String anoTexto = jTextField2.getText().trim();
    String marca = (String) jComboBox1.getSelectedItem();
    String modelo = (String) jComboBox2.getSelectedItem();

    // Validar que todos los campos estén completos
    if (matricula.isEmpty() || anoTexto.isEmpty() || "Seleccione una marca".equals(marca) || "Seleccione un modelo".equals(modelo)) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar el formato de la matrícula: 4 números seguidos de 3 letras
    if (!esMatriculaValida(matricula)) {
        JOptionPane.showMessageDialog(this, "La matrícula debe tener el formato de 4 números seguidos por 3 letras (por ejemplo: 1234ABC)", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar que el año sea un valor numérico y de 4 dígitos
    if (!esAnoValido(anoTexto)) {
        JOptionPane.showMessageDialog(this, "El año debe ser un número de 4 dígitos", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int ano = Integer.parseInt(anoTexto);
        // Validar que el año esté en un rango válido
        if (ano < 1886 || ano > 2100) { // Supongamos que el rango de años es entre 1886 (primer automóvil) y 2100
            JOptionPane.showMessageDialog(this, "El año debe estar entre 1886 y 2100", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el objeto coche y guardarlo
        CochesDTO coche = new CochesDTO();
        coche.setMatricula(matricula);
        coche.setAnoMatriculacion(ano);
        coche.setMarca(marca);
        coche.setModelo(modelo);

        cochesServicio.agregarCoche(coche);
        JOptionPane.showMessageDialog(this, "Vehículo agregado exitosamente");
        dispose();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El año debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al agregar el vehículo: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// Método para validar que la matrícula tenga el formato correcto: 4 números seguidos por 3 letras
private boolean esMatriculaValida(String matricula) {
    return matricula.matches("^[0-9]{4}[A-Z]{3}$"); // 4 números seguidos de 3 letras mayúsculas
}

// Método para verificar si el año es válido (debe ser un número de cuatro dígitos)
private boolean esAnoValido(String ano) {
    return ano.matches("^[0-9]{4}$");
}


    private void configurarEncabezadoTabla() {
        jButton1.setBackground(new java.awt.Color(0, 128, 0));
        jButton2.setBackground(new java.awt.Color(255, 0, 0));
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Vehículo");

        jLabel1.setText("Matrícula:");

        jLabel2.setText("Año:");

        jLabel3.setText("Marca:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Modelo:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        agregarVehiculo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
